Баталова С.А., 'Ls', гр. 3530901/20003
Saloed/softdev-2023-spring-task-2 pull request #12
Opened 2023-04-02 13:24 UTC by FeelingIcy

Так и не получилось заставить тесты работать. Не совсем понимаю, в чем проблема

2023-04-06 09:24 UTC, Saloed requested changes

2023-04-06 09:24 UTC, Saloed commented on src/main/java/FileInfo.java
> +    public String toString(Args args) {
Так собирать строку по кусочкам нехорошо, т.к. каждый раз строка копируется. Лучше завести StringBuilder и его сюда передавать

2023-04-06 09:26 UTC, Saloed commented
Вы в тестах явно используете \r\n. Это lineSeparator, специфичный для windows. Лучше использовать System.lineSeparator, т.к. он будет всегда правильный

2023-04-10 13:53 UTC, Saloed requested changes

2023-04-10 13:53 UTC, Saloed commented on src/main/java/FileInfoList.java
> +    public static Set<String> setOfFiles = new HashSet<>();
Ради тестов заводить глобальное изменяемое поле это нехорошо. Возможно, в тестах лучше вызывать не `main`,  а что-то другое.

2023-04-10 13:53 UTC, Saloed commented on src/main/java/FileInfoList.java
> +        if (args.out == null) {
Можно сделать функцию, которая принимает `OutputStream` и передавать в неё либо файл либо `System.out`.

2023-04-10 13:53 UTC, Saloed commented on src/main/java/FileInfo.java
> +        names.add(fileToSet.replaceAll(" \\d+/\\d+/\\d+ \\d+:\\d+:\\d+",""));
Что-то странное

2023-04-17 09:00 UTC, Saloed commented on src/main/java/FileInfoList.java
> +        if (args.out == null) {
Всё ещё стоит сделать такую функцию, т.к. хочется не дублировать цикл.

2023-04-17 23:49 UTC, FeelingIcy commented on src/main/java/FileInfoList.java
> +        if (args.out == null) {
Пока писала код, поняла, что можно в принципе и не выносить это в отдельную функцию, поэтому просто переделала так, чтобы избавиться от дублирования цикла. Сделала через BufferedWriter.

2023-04-21 11:22 UTC, Saloed approved these changes

2023-04-21 11:22 UTC, closed without merging