Гусев, find, гр. 3530901/20003
Saloed/softdev-2023-spring-task-2 pull request #13
Opened 2023-04-03 17:25 UTC by Chrisnisch

2023-04-06 09:37 UTC, Saloed requested changes

2023-04-06 09:37 UTC, Saloed commented on task/src/main/java/task2/Parser.java
> +    public ArrayList<String> parse(String[] args) throws IOException {
Лучше указывать более общий тип List

2023-04-06 09:37 UTC, Saloed commented on task/src/main/java/task2/Finder.java
> +            Pattern p = Pattern.compile(fileName, Pattern.CASE_INSENSITIVE);
А это нормально работает, если в имени файла есть, например, точки?

2023-04-06 09:48 UTC, Chrisnisch commented on task/src/main/java/task2/Finder.java
> +            Pattern p = Pattern.compile(fileName, Pattern.CASE_INSENSITIVE);
да, сейчас добавлю тест для этого случая

2023-04-17 09:06 UTC, Saloed requested changes

2023-04-17 09:06 UTC, Saloed commented on task/src/main/java/task2/Finder.java
> +        ArrayList<File> fileList = new ArrayList<>();
Лучше указывать более общий тип `List`

2023-04-17 09:06 UTC, Saloed commented on task/src/main/java/task2/Parser.java
> +        return new TreeSet<>(finder.find());
А зачем оборачивать в новый `Set`?

2023-04-17 09:06 UTC, Saloed commented on task/src/main/java/task2/Finder.java
> +            Pattern p = Pattern.compile(fileName, Pattern.CASE_INSENSITIVE);
Проверьте случаи с файлами типа `a.b.c.txt` и `axbxc.txt`

2023-04-21 11:59 UTC, Saloed reviewed
4

2023-04-21 11:59 UTC, Saloed commented on task/src/test/java/task2/FindTests.java
> +        String[] input = {"-r", "a.b.c.txt"};
Если у вас будет файл `axbxc.txt`, то этот тест не пройдёт. Хотя должен.

2023-04-21 11:59 UTC, closed without merging