Куликов Н. В., "Split", гр. 3530901/20003
Saloed/softdev-2023-spring-task-2 pull request #14
Opened 2023-04-05 08:05 UTC by Rokossovskiy

2023-04-06 09:50 UTC, Saloed requested changes

2023-04-06 09:50 UTC, Saloed commented on src/main/java/Splitter.java
> +    private void initialize(String[] args) {
Для парсинга аргументов лучше взять какую-то готовую библиотеку

2023-04-06 09:50 UTC, Saloed commented on src/main/java/Splitter.java
> +    boolean flag_D = false; //Означает, что выходные файлы следует называть ofile1...
В java принято использовать camelCase

2023-04-06 09:50 UTC, Saloed commented on src/main/java/Splitter.java
> +                wr.write(files.get(i));
Лучше использовать try-with-resources

2023-04-06 09:50 UTC, Saloed commented on src/main/java/Splitter.java
> +            result.add(String.join("\r\n", content.subList(0, sizeFile)));
\r\n это разделитель, специфичный для windows

2023-04-10 14:10 UTC, Saloed requested changes

2023-04-10 14:10 UTC, Saloed commented on src/main/java/Splitter.java
> +        try (ByteArrayOutputStream newFileName = new ByteArrayOutputStream()) {
Можно сразу добавлять символы в `StringBuilder` и не заводить `ByteArrayOutputStream`.

2023-04-10 14:10 UTC, Saloed commented on src/main/java/Splitter.java
> +                newFileName.write(chars.charAt(i % 26));
Лучше не `26`, а `chars.length`

2023-04-10 14:10 UTC, Saloed commented on src/main/java/Splitter.java
> +                content.subList(0, sizeFile).clear();
Лучше не модифицировать список, т.к. такие операции всё время будут полностью его копировать.

2023-04-17 09:14 UTC, Saloed requested changes

2023-04-17 09:14 UTC, Saloed commented on src/main/java/Splitter.java
> +    private byte[][] splitFile() throws IOException {
Получается немного странно, что у нас всё равно для этого случая заполняется поле `content`, которое не используется.

2023-04-17 13:52 UTC, Rokossovskiy commented on src/main/java/Splitter.java
> +    private byte[][] splitFile() throws IOException {
И как это исправить?

2023-04-21 12:01 UTC, Saloed commented on src/main/java/Splitter.java
> +    private byte[][] splitFile() throws IOException {
Ну проще всего не заполнять `content` сразу, а делать это отдельно для каждого случая и по разному.

2023-04-21 12:01 UTC, closed without merging