Жук В. Д. 3530901/20003 uniq
Saloed/softdev-2023-spring-task-2 pull request #15
Opened 2023-04-05 09:09 UTC by vasilisazhuk

Я не совсем понимаю, как сделать сборку

2023-04-06 11:01 UTC, Saloed requested changes

2023-04-10 13:09 UTC, Saloed requested changes

2023-04-10 13:09 UTC, Saloed commented on src/main/java/ConsoleApp.java
> +        Parser pars = new Parser(args);
А почему не `UniqParser`?

2023-04-10 13:09 UTC, Saloed commented on src/main/java/ConsoleApp.java
> +    static void outputStream(List<String> list) {
Можно сделать функцию, которая принимает `OtputStream` и в одном случае передать туда файл, а в другом `System.out`

2023-04-10 13:09 UTC, Saloed commented on src/main/java/ConsoleApp.java
> +                if (!actualLine.toLowerCase(Locale.ROOT).equals(previousLine.toLowerCase())) {
Ветки `if` лучше как-то объединить, чтобы код не дублировался

2023-04-10 13:09 UTC, Saloed commented on src/main/java/ConsoleApp.java
> +        list = readOut(input);
Эту переменную лучше прямо здесь и объявить

2023-04-10 16:02 UTC, vasilisazhuk commented on src/main/java/Pair.java
> +        Pair<Integer, String> pair = (Pair<Integer, String>) o;
хотела как-то явно указать что пара число, строка, потом поняла что не надо и забыла поменять обратно

2023-04-17 10:22 UTC, Saloed requested changes

2023-04-17 10:22 UTC, Saloed commented on src/main/java/Parser.java
> +public class Parser {
Если этот класс не используется, то его лучше удалить

2023-04-17 10:22 UTC, Saloed commented on src/main/java/ConsoleApp.java
> +    static List<String> unique (List<String> input, boolean sen, boolean ignore, int num) {
Лучше давать аргументам чуть более полные имена, чтобы из них было понятно, за что они отвечают. Сейчас, вообще не очевидно, что `sen` это `ignoreCase`, а `ignore`, это вообще про  пропуск `num` символов.

2023-04-17 10:22 UTC, Saloed commented on src/main/java/ConsoleApp.java
> +    static List<String> defaultFun (List<String> input, boolean sen, boolean ignore, int num) {
Здесь лучше тоже использовать `counting` и не дублировать код

2023-04-17 10:22 UTC, Saloed commented on src/main/java/ConsoleApp.java
> +        String previousLine = "";
Пустые строки из файла тоже хочется обрабатывать правильно, так что лучше это как-то обработать отдельно.

2023-04-17 10:22 UTC, Saloed commented on src/main/java/ConsoleApp.java
> +                if (num < a.length() && num < b.length()){
А если только один меньше? А если равны? Кажется, тут во всех случаях нужно что-то сделать. Например, присвоить пустую строку.

2023-04-21 12:05 UTC, Saloed approved these changes

2023-04-21 12:05 UTC, closed without merging