Task2Ready
Saloed/softdev-2023-spring-task-2 pull request #16
Opened 2023-04-06 20:18 UTC by likholetovks

Лихолетов Кирилл 3530901/20005 "Du"

2023-04-10 13:14 UTC, Saloed requested changes

2023-04-10 13:14 UTC, Saloed commented on src/main/java/Functions.java
> +        double mb = size / k / k;
Лучше:
```
 double kb = b / k;
 double mb = kb / k;
 ...
```

2023-04-10 13:14 UTC, Saloed commented on src/main/java/Functions.java
> +    private final ArrayList<Long> list;
Лучше указывать более общий тип `List`

2023-04-10 13:14 UTC, Saloed commented on src/main/java/Du.java
> +    public static String answer;
Лучше не заводить таких переменных. Лучше в тестах вызывать не `main`, а создавать `Functions`  и с ним работать.

2023-04-21 12:12 UTC, Saloed reviewed
4

2023-04-21 12:12 UTC, Saloed commented on src/main/java/Functions.java
> +        DecimalFormat df = new DecimalFormat("#.##");
А зачем вы создали `format` а потом его не используете?

2023-04-21 12:12 UTC, Saloed commented on src/main/java/Functions.java
> +    public String outForTest() {
Полностью дублировать кусок кода только ради тестов нехорошо. Лучше было бы либо реализовать вывод в `OutputStream` и в тестах передавать специальный, либо и в обычном случае использовать `StringBuilder`.

2023-04-21 12:12 UTC, closed without merging

2023-04-21 17:22 UTC, likholetovks commented on src/main/java/Functions.java
> +        DecimalFormat df = new DecimalFormat("#.##");
Тестировал разные способы, забыл убрать