Плеханов А.Е., 'tar', гр. 3530901/20003
Saloed/softdev-2023-spring-task-2 pull request #2
Opened 2023-02-19 22:58 UTC by Plezha

i'm alternatively intelligent

2023-02-20 10:01 UTC, Saloed requested changes
1. Директорию `build` в репозиторий добавлять не нужно
2. Тесты должны проходить

2023-02-21 16:17 UTC, Plezha commented on app/src/main/kotlin/softdevSpringTask/tar.kt
> +fun readLine(inputStream: FileInputStream): String {
`bufferedReader` не умеет читать байты

2023-02-22 13:26 UTC, Plezha commented on app/src/main/kotlin/softdevSpringTask/tar.kt
> +fun readLine(inputStream: FileInputStream): String {
А у `bufferedReader` есть `readNBytes `?

2023-02-22 13:26 UTC, Plezha commented on app/src/main/kotlin/softdevSpringTask/tar.kt
> +fun readLine(inputStream: FileInputStream): String {
Или хоть какой-то механизм, позволяющий это релаизовать

2023-02-25 15:51 UTC, Saloed requested changes
Тесты на ci всё ещё не проходят

2023-02-25 15:51 UTC, Saloed commented on app/src/main/kotlin/softdevSpringTask/tar.kt
> +        fun addFileContent(fileToCopy: File, outputFileOutputStream: OutputStream) {
Лучше не делать функции локальными

2023-02-28 11:46 UTC, Saloed requested changes

2023-02-28 11:46 UTC, Saloed commented on app/src/main/kotlin/softdevSpringTask/tar.kt
> +    val readChar = { inputStream.read().toChar() }
Локальная лямбда? А это точно нужно?

2023-02-28 11:46 UTC, Saloed commented on app/src/main/kotlin/softdevSpringTask/tar.kt
> +                            val buffer = ByteArray(min(remainingFileLength, DEFAULT_BUFFER_SIZE))
Можно выделить этот буффер один раз и дальше его переиспользовать

2023-03-03 08:12 UTC, Saloed approved these changes

2023-03-03 08:12 UTC, closed without merging