Шаров М.А. pack-rle гр. 3530901/20005
Saloed/softdev-2023-spring-task-2 pull request #3
Opened 2023-02-25 16:14 UTC by Tamvey

2023-02-25 16:49 UTC, Saloed requested changes
Не нужно каждый раз новый pr открывать

2023-02-25 16:49 UTC, Saloed commented on src/test/java/com/tests/AppTest.java
> +                String nameIn = "." + File.separator + "inputTestFile.txt";
Лучше использовать всякие Paths.get.

2023-02-25 16:49 UTC, Saloed commented on src/main/java/com/utility/App.java
> +                if (outputFileName == null) {
Это лучше вынести и не дублировать

2023-02-25 16:49 UTC, Saloed commented on src/main/java/com/utility/Coder.java
> +                if (bytes.size() == 63) {
Эту константу лучше куда-то вынести

2023-02-25 16:49 UTC, Saloed commented on src/main/java/com/utility/Coder.java
> +        else if (bytes.size() == 1 || bytes.get(0) == bytes.get(1)) {
Это выглядит не очень очевидно.

2023-02-25 16:49 UTC, Saloed commented on src/main/java/com/utility/Coder.java
> +            List<Byte> bytes = new LinkedList<>();
Лучше использовать ArrayList

2023-02-25 16:49 UTC, Saloed commented on src/main/java/com/utility/Coder.java
> +                } else if (now == bytes.get(bytes.size() - 1)) {
Кажется, лучше как-то более явно сделать режим, в котором мы сейчас находимся

2023-02-25 16:49 UTC, Saloed commented on src/main/java/com/utility/Coder.java
> +                if (bytes.size() == 63) {
И почему 63, а не 128?

2023-02-25 17:04 UTC, Tamvey commented on src/main/java/com/utility/Coder.java
> +                if (bytes.size() == 63) {
Пытался отнести отрицательные числа к неповторяющейся последовательности, а положительные - к повторяющейся, но не выходило, сделал всё через положительные, 63 поскольку, если будет неповторяющяся последовательность длинной в 64 символа, то будет переполнение байта.
```
bw.write((byte) (64 + bytes.size()));
```

2023-03-03 08:09 UTC, Saloed requested changes

2023-03-06 10:03 UTC, Saloed commented on src/main/java/com/utility/Coder.java
> +                        size = -1;
А после записи массива точно не нужно делать `bytes[0] = now`?

2023-03-09 16:59 UTC, Saloed approved these changes

2023-03-09 17:00 UTC, closed without merging